### ISSUE TITLE
网关上配置重试策略servicecomb.retry中maxAttempts最大尝试次数无效

### ISSUE THREAD

**Issue by Giannuo** [huaweicloud/spring-cloud-huawei#580]
参考integration-tests/cse-v1。
spring-cloud-huawei网关上，代码调试确认配置已生效的情况下，配置重试策略servicecomb.retry中maxAttempts最大尝试次数无效，一直重试到正确响应为止；
对比consumer向下调用provider，在consumer上配置则生效。

**Comment by zhaozw** [comment]
调试了一下，发现应该是代码问题，
retry.context()每次都会重新创建一个ContextImpl，而toRun.transform(RetryOperator.of(retry))是创建一个AsyncContextImpl，导致每次onComplete的时候调用的是AsyncContextImpl的onComplete方法里面的numOfAttempts.get()的值一直是0，然后下面调用的是新建的ContextImpl的onResult，然后对ContextImpl的numOfAttempts进行自增，应该是对之前的AsyncContextImpl的对象的numOfAttempts进行自增。
1 由于没找到切入点直接复制粘贴了RetryOperator进行少量改动确保两次调用的是同一个对象。
2 还有就是泛型那里没处理好，用的@SuppressWarnings("unchecked")，否则构建的时候报错。

因为无法上传文件，下面贴出补丁，可以解决这个bug，由于1和2，应该有更好的解决办法。

diff --git a/spring-cloud-starter-huawei/spring-cloud-starter-huawei-service-engine-gateway/src/main/java/com/huaweicloud/gateway/governance/GovernanceGatewayFilterFactory.java b/spring-cloud-starter-huawei/spring-cloud-starter-huawei-service-engine-gateway/src/main/java/com/huaweicloud/gateway/governance/GovernanceGatewayFilterFactory.java
index e44528a..d00a354 100644
--- a/spring-cloud-starter-huawei/spring-cloud-starter-huawei-service-engine-gateway/src/main/java/com/huaweicloud/gateway/governance/GovernanceGatewayFilterFactory.java
+++ b/spring-cloud-starter-huawei/spring-cloud-starter-huawei-service-engine-gateway/src/main/java/com/huaweicloud/gateway/governance/GovernanceGatewayFilterFactory.java
@@ -48,7 +48,6 @@
 import io.github.resilience4j.reactor.bulkhead.operator.BulkheadOperator;
 import io.github.resilience4j.reactor.circuitbreaker.operator.CircuitBreakerOperator;
 import io.github.resilience4j.reactor.ratelimiter.operator.RateLimiterOperator;
-import io.github.resilience4j.reactor.retry.RetryOperator;
 import io.github.resilience4j.retry.Retry;
 import reactor.core.publisher.Mono;
 
@@ -103,13 +102,15 @@
       }
     }
 
+    @SuppressWarnings("unchecked")
     private Mono<Void> addRetry(ServerWebExchange exchange, GovernanceRequest governanceRequest, Mono<Void> toRun) {
       Retry retry = retryHandler.getActuator(governanceRequest);
       if (retry != null) {
-        toRun = toRun.transform(RetryOperator.of(retry))
+        final RetryOperator ro = RetryOperator.of(retry);
+        toRun = toRun.transform(ro)
             .doOnSuccess(v -> {
               if (exchange.getResponse().getRawStatusCode() != null) {
-                if (retry.context().onResult(exchange.getResponse().getRawStatusCode())) {
+                if (ro.handleResult(exchange.getResponse().getRawStatusCode())!=-1) {
                   exchange.getResponse().setStatusCode(null);
                   reset(exchange);
                   throw new RetryException();
diff --git a/spring-cloud-starter-huawei/spring-cloud-starter-huawei-service-engine-gateway/src/main/java/com/huaweicloud/gateway/governance/RetryOperator.java b/spring-cloud-starter-huawei/spring-cloud-starter-huawei-service-engine-gateway/src/main/java/com/huaweicloud/gateway/governance/RetryOperator.java
index ff038a8..ca04557 100644
--- a/spring-cloud-starter-huawei/spring-cloud-starter-huawei-service-engine-gateway/src/main/java/com/huaweicloud/gateway/governance/RetryOperator.java
+++ b/spring-cloud-starter-huawei/spring-cloud-starter-huawei-service-engine-gateway/src/main/java/com/huaweicloud/gateway/governance/RetryOperator.java
@@ -1,2 +1,111 @@
-package com.huaweicloud.gateway.governance;public class RetryOperator {
+package com.huaweicloud.gateway.governance;
+
+
+import io.github.resilience4j.reactor.IllegalPublisherException;
+import io.github.resilience4j.retry.Retry;
+import org.reactivestreams.Publisher;
+import reactor.core.publisher.Flux;
+import reactor.core.publisher.Mono;
+
+import java.time.Duration;
+import java.util.function.UnaryOperator;
+
+/**
+ * A Reactor Retry operator which wraps a reactive type in a Retry.
+ *
+ * @param <T> the value type of the upstream and downstream
+ */
+public class RetryOperator<T> implements UnaryOperator<Publisher<T>> {
+
+
+    private final Retry retry;
+    private Context<T> context;
+
+    private RetryOperator(Retry retry) {
+        this.retry = retry;
+    }
+
+    /**
+     * Creates a retry.
+     *
+     * @param <T>   the value type of the upstream and downstream
+     * @param retry the retry
+     * @return a RetryOperator
+     */
+    public static <T> RetryOperator<T> of(Retry retry) {
+        return new RetryOperator<>(retry);
+    }
+
+    @Override
+    public Publisher<T> apply(Publisher<T> publisher) {
+        if (publisher instanceof Mono) {
+            context = new Context<>(retry.asyncContext());
+            Mono<T> upstream = (Mono<T>) publisher;
+            return upstream.doOnNext(context::handleResult)
+                    .retryWhen(reactor.util.retry.Retry.withThrowable(errors -> errors.flatMap(context::handleErrors)))
+                    .doOnSuccess(t -> {
+                        context.onComplete();
+
+                    });
+        } else if (publisher instanceof Flux) {
+            context = new Context<>(retry.asyncContext());
+            Flux<T> upstream = (Flux<T>) publisher;
+            return upstream.doOnNext(context::handleResult)
+                    .retryWhen(reactor.util.retry.Retry.withThrowable(errors -> errors.flatMap(context::handleErrors)))
+                    .doOnComplete(context::onComplete);
+        } else {
+            throw new IllegalPublisherException(publisher);
+        }
+    }
+
+    public long handleResult(T result) {
+        return context.handleResult(result);
+    }
+
+    private static class Context<T> {
+
+        private final Retry.AsyncContext<T> retryContext;
+
+        Context(Retry.AsyncContext<T> retryContext) {
+            this.retryContext = retryContext;
+        }
+
+        void onComplete() {
+            this.retryContext.onComplete();
+        }
+
+        long handleResult(T result) {
+            return retryContext.onResult(result);
+        }
+
+        Publisher<Long> handleErrors(Throwable throwable) {
+            if (throwable instanceof Context.RetryDueToResultException) {
+                long waitDurationMillis = ((RetryDueToResultException) throwable).waitDurationMillis;
+                return Mono.delay(Duration.ofMillis(waitDurationMillis));
+            }
+            // Filter Error to not retry on it
+            if (throwable instanceof Error) {
+                throw (Error) throwable;
+            }
+
+            long waitDurationMillis = retryContext.onError(throwable);
+
+            if (waitDurationMillis == -1) {
+                return Mono.error(throwable);
+            }
+
+            return Mono.delay(Duration.ofMillis(waitDurationMillis));
+        }
+
+        public static class RetryDueToResultException extends RuntimeException {
+            static final long serialVersionUID = -7034897190745766939L;
+            private final long waitDurationMillis;
+
+            RetryDueToResultException(long waitDurationMillis) {
+                super("retry due to retryOnResult predicate");
+                this.waitDurationMillis = waitDurationMillis;
+            }
+        }
+    }
 }
+

**Comment by Giannuo** [comment]
计划哪个版本修复？
